--------------------------------------------------------
--  File created - segunda-feira-setembro-29-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TASY_SYNC_LOGS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TASY_SYNC_LOGS" 
   (	"LOG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LOG_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"LOG_TYPE" VARCHAR2(20 BYTE), 
	"LOG_MESSAGE" VARCHAR2(4000 BYTE), 
	"TABLE_NAME" VARCHAR2(100 BYTE), 
	"RECORD_COUNT" NUMBER, 
	"SYNC_TYPE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TASY_SYNC_LOGS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_TASY_SYNC_LOGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_TASY_SYNC_LOGS" ON "SYSTEM"."TASY_SYNC_LOGS" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TASY_SYNC_LOGS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TASY_SYNC_LOGS" MODIFY ("LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TASY_SYNC_LOGS" ADD CONSTRAINT "PK_TASY_SYNC_LOGS" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
