--------------------------------------------------------
--  File created - segunda-feira-setembro-29-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TASY_IDIOMA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TASY_IDIOMA" 
   (	"NR_SEQUENCIA" NUMBER(10,0), 
	"DT_ATUALIZACAO" DATE, 
	"NM_USUARIO" VARCHAR2(15 CHAR), 
	"DT_ATUALIZACAO_NREC" DATE, 
	"NM_USUARIO_NREC" VARCHAR2(15 CHAR), 
	"DS_IDIOMA" VARCHAR2(80 CHAR), 
	"CD_EXP_IDIOMA" NUMBER(10,0), 
	"DS_LANGUAGE_TAG" VARCHAR2(8 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TASY_DATA" ;
REM INSERTING into SYSTEM.TASY_IDIOMA
SET DEFINE OFF;
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (1,to_date('07-JAN-15','DD-MON-RR'),'Rafael',to_date('05-JUN-13','DD-MON-RR'),'bcgucowski','Português (BR)',349249,'pt_BR');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (2,to_date('07-JAN-15','DD-MON-RR'),'Rafael',to_date('07-FEB-14','DD-MON-RR'),'Fernando','Espanhol (MX)',614648,'es_MX');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (3,to_date('07-JAN-15','DD-MON-RR'),'Rafael',to_date('18-MAR-09','DD-MON-RR'),'Rafael','Espanhol (CO)',349251,'es_CO');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (4,to_date('07-JAN-15','DD-MON-RR'),'Rafael',to_date('05-JUN-13','DD-MON-RR'),'bcgucowski','Espanhol (AR)',349253,'es_AR');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (5,to_date('07-JAN-15','DD-MON-RR'),'Rafael',to_date('07-FEB-14','DD-MON-RR'),'Fernando','Inglês (US)',614649,'en_US');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (7,to_date('17-DEC-15','DD-MON-RR'),'Fernando',null,null,'Alemão (DE)',null,'de_DE');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (6,to_date('03-SEP-15','DD-MON-RR'),'rbwessler',null,null,'Inglês (UK)',691419,'en_GB');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (8,to_date('13-OCT-16','DD-MON-RR'),'Fernando',null,null,'Árabe (SA)',null,'ar_SA');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (9,to_date('30-JUL-18','DD-MON-RR'),'Martini',null,null,'Inglês (AU)',888425,'en_AU');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (12,to_date('08-JUL-20','DD-MON-RR'),'lcgardella',null,null,'Japonês (JP)',773562,'ja_JP');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (13,to_date('08-JUL-20','DD-MON-RR'),'dutpadel',null,null,'Espanhol (DO)',942434,'es_DO');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (11,to_date('11-DEC-18','DD-MON-RR'),'jrfusinato',null,null,'Polonês (PL)',632355,'pl_PL');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (14,to_date('20-AUG-20','DD-MON-RR'),'ifschmitt',null,null,'Alemão (AT)',1025631,'de_AT');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (15,to_date('17-SEP-20','DD-MON-RR'),'JVVPPEREIRA',null,null,'Espanhol (BO)',1028946,'es_BO');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (22,to_date('03-JUN-24','DD-MON-RR'),'ifschmitt',null,null,'Holandês (NL)',945611,'nl_NL');
Insert into SYSTEM.TASY_IDIOMA (NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,DS_IDIOMA,CD_EXP_IDIOMA,DS_LANGUAGE_TAG) values (16,to_date('28-MAY-22','DD-MON-RR'),'lcgardella',null,null,'Francês (FR)',1057876,'fr_FR');
--------------------------------------------------------
--  DDL for Index TASYIDI_I1
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."TASYIDI_I1" ON "SYSTEM"."TASY_IDIOMA" ("DS_LANGUAGE_TAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 16384 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TASYIDI_DICEXPR_FK_I
--------------------------------------------------------

  CREATE INDEX "SYSTEM"."TASYIDI_DICEXPR_FK_I" ON "SYSTEM"."TASY_IDIOMA" ("CD_EXP_IDIOMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 16384 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TASYIDI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TASYIDI_PK" ON "SYSTEM"."TASY_IDIOMA" ("NR_SEQUENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TASY_IDIOMA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TASY_IDIOMA" ADD CONSTRAINT "TASYIDI_PK" PRIMARY KEY ("NR_SEQUENCIA")
  USING INDEX "SYSTEM"."TASYIDI_PK"  ENABLE;
