--------------------------------------------------------
--  File created - segunda-feira-setembro-29-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TASY_SYNC_CONTROL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TASY_SYNC_CONTROL" 
   (	"TABLE_NAME" VARCHAR2(100 BYTE), 
	"LAST_SYNC" TIMESTAMP (6), 
	"RECORD_COUNT" NUMBER DEFAULT 0, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'ACTIVE', 
	"KEY_COLUMN" VARCHAR2(100 BYTE), 
	"SYNC_FILTER" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TASY_SYNC_CONTROL
SET DEFINE OFF;
Insert into SYSTEM.TASY_SYNC_CONTROL (TABLE_NAME,LAST_SYNC,RECORD_COUNT,STATUS,KEY_COLUMN,SYNC_FILTER) values ('USUARIO',to_timestamp('01-AUG-25 06.06.38.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),8138,'ACTIVE','NM_USUARIO',null);
Insert into SYSTEM.TASY_SYNC_CONTROL (TABLE_NAME,LAST_SYNC,RECORD_COUNT,STATUS,KEY_COLUMN,SYNC_FILTER) values ('CPOE_DIETA',null,0,'ACTIVE','NR_SEQUENCIA',null);
Insert into SYSTEM.TASY_SYNC_CONTROL (TABLE_NAME,LAST_SYNC,RECORD_COUNT,STATUS,KEY_COLUMN,SYNC_FILTER) values ('CPOE_MATERIAL',null,0,'ACTIVE','NR_SEQUENCIA',null);
Insert into SYSTEM.TASY_SYNC_CONTROL (TABLE_NAME,LAST_SYNC,RECORD_COUNT,STATUS,KEY_COLUMN,SYNC_FILTER) values ('CPOE_PROCEDIMENTO',null,0,'ACTIVE','NR_SEQUENCIA',null);
Insert into SYSTEM.TASY_SYNC_CONTROL (TABLE_NAME,LAST_SYNC,RECORD_COUNT,STATUS,KEY_COLUMN,SYNC_FILTER) values ('CPOE_GASOTERAPIA',null,0,'ACTIVE','NR_SEQUENCIA',null);
Insert into SYSTEM.TASY_SYNC_CONTROL (TABLE_NAME,LAST_SYNC,RECORD_COUNT,STATUS,KEY_COLUMN,SYNC_FILTER) values ('CPOE_RECOMENDACAO',null,0,'ACTIVE','NR_SEQUENCIA',null);
Insert into SYSTEM.TASY_SYNC_CONTROL (TABLE_NAME,LAST_SYNC,RECORD_COUNT,STATUS,KEY_COLUMN,SYNC_FILTER) values ('CPOE_HEMOTERAPIA',null,0,'ACTIVE','NR_SEQUENCIA',null);
Insert into SYSTEM.TASY_SYNC_CONTROL (TABLE_NAME,LAST_SYNC,RECORD_COUNT,STATUS,KEY_COLUMN,SYNC_FILTER) values ('CPOE_DIALISE',null,0,'ACTIVE','NR_SEQUENCIA',null);
Insert into SYSTEM.TASY_SYNC_CONTROL (TABLE_NAME,LAST_SYNC,RECORD_COUNT,STATUS,KEY_COLUMN,SYNC_FILTER) values ('CPOE_INTERVENCAO',null,0,'ACTIVE','NR_SEQUENCIA',null);
Insert into SYSTEM.TASY_SYNC_CONTROL (TABLE_NAME,LAST_SYNC,RECORD_COUNT,STATUS,KEY_COLUMN,SYNC_FILTER) values ('CPOE_ANATOMIA_PATOLOGICA',null,0,'ACTIVE','NR_SEQUENCIA',null);
--------------------------------------------------------
--  DDL for Index SYS_C008591
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008591" ON "SYSTEM"."TASY_SYNC_CONTROL" ("TABLE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TASY_SYNC_CONTROL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TASY_SYNC_CONTROL" ADD PRIMARY KEY ("TABLE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
