--------------------------------------------------------
--  File created - segunda-feira-setembro-29-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TASY_SYSTEM_CONFIG
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TASY_SYSTEM_CONFIG" 
   (	"CONFIG_KEY" VARCHAR2(100 BYTE), 
	"CONFIG_VALUE" VARCHAR2(1000 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"LAST_UPDATED" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" VARCHAR2(50 BYTE) DEFAULT 'SYSTEM'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TASY_SYSTEM_CONFIG
SET DEFINE OFF;
Insert into SYSTEM.TASY_SYSTEM_CONFIG (CONFIG_KEY,CONFIG_VALUE,DESCRIPTION,LAST_UPDATED,UPDATED_BY) values ('SYNC_INTERVAL','900','Intervalo entre sincronizações em segundos',to_timestamp('21-JUL-25 03.46.04.306000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM');
Insert into SYSTEM.TASY_SYSTEM_CONFIG (CONFIG_KEY,CONFIG_VALUE,DESCRIPTION,LAST_UPDATED,UPDATED_BY) values ('RETRY_INTERVAL','60','Intervalo entre tentativas de reconexão em segundos',to_timestamp('21-JUL-25 03.46.04.313000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM');
Insert into SYSTEM.TASY_SYSTEM_CONFIG (CONFIG_KEY,CONFIG_VALUE,DESCRIPTION,LAST_UPDATED,UPDATED_BY) values ('MAX_RETRIES','5','Número máximo de tentativas de reconexão',to_timestamp('21-JUL-25 03.46.04.320000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM');
--------------------------------------------------------
--  DDL for Index SYS_C008584
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008584" ON "SYSTEM"."TASY_SYSTEM_CONFIG" ("CONFIG_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TASY_SYSTEM_CONFIG
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TASY_SYSTEM_CONFIG" ADD PRIMARY KEY ("CONFIG_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
